name: af3
channels:
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2025.11.4=hd43f75c_0
  - expat=2.7.3=hc366171_0
  - hmmer=3.4=h80f0ee0_3
  - ld_impl_linux-aarch64=2.44=h4e4ac68_2
  - libffi=3.4.4=h419075a_1
  - libgcc=15.2.0=hc18542e_7
  - libgcc-ng=15.2.0=h51576c1_7
  - libgomp=15.2.0=hf47c802_7
  - libnsl=2.0.0=h998d150_0
  - libstdcxx=15.2.0=h9538471_7
  - libstdcxx-ng=15.2.0=h719ae8e_7
  - libuuid=1.41.5=h998d150_0
  - libxcb=1.17.0=hf66535e_0
  - libzlib=1.3.1=h998d150_0
  - ncurses=6.5=h419075a_0
  - openssl=3.0.18=h8a9c3cf_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=hfd63f10_1
  - python=3.12.12=h71d72b8_1
  - readline=8.3=h886d1d0_0
  - setuptools=80.9.0=py312hd43f75c_0
  - sqlite=3.51.0=hc5b20ee_0
  - tk=8.6.15=h987d8db_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312hd43f75c_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - zlib=1.3.1=h998d150_0
  - pip:
      - absl-py==2.3.1
      - alphafold3==3.0.1
      - asttokens==3.0.1
      - attrs==25.4.0
      - comm==0.2.3
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.2.2
      - debugpy==1.8.17
      - decorator==5.2.1
      - dm-haiku==0.0.15
      - dm-tree==0.1.9
      - executing==2.2.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - iniconfig==2.3.0
      - ipykernel==7.1.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - jax==0.8.1
      - jax-cuda13-pjrt==0.8.1
      - jax-cuda13-plugin==0.8.1
      - jax-triton==0.3.0
      - jaxlib==0.8.1
      - jaxtyping==0.3.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmp==0.0.4
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - markupsafe==3.0.2
      - matplotlib-inline==0.2.1
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - ninja==1.13.0
      - numpy==2.3.5
      - nvidia-cublas==13.1.0.3
      - nvidia-cuda-crt==13.0.88
      - nvidia-cuda-cupti==13.0.85
      - nvidia-cuda-nvcc==13.0.88
      - nvidia-cuda-nvrtc==13.0.88
      - nvidia-cuda-runtime==13.0.96
      - nvidia-cudnn-cu13==9.13.0.50
      - nvidia-cufft==12.0.0.61
      - nvidia-cufile==1.15.1.6
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.4.66
      - nvidia-cusparse==12.6.3.3
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.27.7
      - nvidia-nvjitlink==13.0.88
      - nvidia-nvshmem-cu13==3.4.5
      - nvidia-nvtx==13.0.85
      - nvidia-nvvm==13.0.88
      - opt-einsum==3.4.0
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==3.0.1
      - pygments==2.19.2
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - rdkit==2024.3.5
      - scipy==1.16.3
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - torch==2.10.0.dev20251121+cu130
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.3.1+gitd654e0f2
      - typeguard==2.13.3
      - typing-extensions==4.15.0
      - wadler-lindig==0.1.7
      - wcwidth==0.2.14
      - wrapt==2.0.1
      - zstandard==0.25.0
prefix: /home/wlt2025/anaconda3/envs/af3
